name: PR to sync staging with master
on:
  push:
    branches:
      - 'master'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging

      - name: Reset staging branch
        run: |
          git fetch origin master:master
          git merge origin/master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ github.token }}
          delete-branch: true
          branch: sync-staging
          title: 're-sync staging with master'
