name: Sync staging to master
on:
  push:
    branches:
      - 'master'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging

      - name: Reset staging branch
          run: |
            git merge origin master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ github.token }}
          #commit-message: Automated merge of master into staging
          #delete-branch: true
          #base: master
          branch: sync-staging
          title: '[automated] Merge Master back to Staging'
